services:
  - type: web
    name: sol-space
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: SESSION_COOKIE_SAMESITE
        value: Lax
      - key: DATABASE_URL
        fromDatabase:
          name: sol-space-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENROUTERAI_API
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false

databases:
  - name: sol-space-db
    databaseName: sol_space
    user: sol_space
